name: Pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
        restore-keys: | 
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: Run pytest
      run: | 
        python -m pytest
    - name: Commit and push changes
      if: always()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        repository: https://${{secrets.TOKEN}}@github.com/vova2228/ConduitPython.git
      run: |
          git remote set-url origin https://${{secrets.TOKEN}}@github.com/vova2228/ConduitPython.git
          git config --global user.email "narutou944@yahoo.com"
          git config --global user.name "vova2228"
          git add ./tests/data/registered_users.xlsx
          git commit -m "Updated test data"
          git push
